name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
      DCP_IP_VERSION_PREFERENCE: ipv4

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install .NET MAUI
        if: matrix.os == 'ubuntu-latest'
        run: dotnet workload install maui-android

      - name: Install .NET MAUI
        if: matrix.os != 'ubuntu-latest'
        run: dotnet workload install maui

      - name: Build solution
        run: dotnet build --configuration Release
