name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Trust developer certificates
        if: matrix.os == 'ubuntu-latest'
        run: dotnet dev-certs https --trust

      - name: Trust developer certificates
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          $pfxPath = Join-Path -Path $(Agent.TempDirectory) -ChildPath 'cert.pfx'
          $password = (New-Guid).ToString("N")
          dotnet dev-certs https --export-path $pfxPath --password $password -v
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          Import-PfxCertificate -FilePath $pfxPath -Password $securePassword -CertStoreLocation Cert:\LocalMachine\Root
          Remove-Item $pfxPath

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
