name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run flaky tests daily at 2 AM UTC
    - cron: '0 2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        test-type: [regular, flaky]
        include:
          - os: windows-latest
            ssl-filter: --filter "Requires!=SSL"
          - test-type: regular
            category-filter: --filter "Category!=Flaky"
            test-name: Test
          - test-type: flaky
            category-filter: --filter "Category=Flaky"
            test-name: Flaky Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Trust developer certificates
        if: matrix.os == 'ubuntu-latest'
        run: dotnet dev-certs https --trust

      - name: Install .NET MAUI
        if: matrix.os == 'ubuntu-latest'
        run: dotnet workload install maui-android

      - name: Install .NET MAUI
        if: matrix.os != 'ubuntu-latest'
        run: dotnet workload install maui

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage" ${{ matrix.category-filter }} ${{ matrix.ssl-filter }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results-${{ matrix.test-type }}-${{ matrix.os }}
          path: |
            **/TestResults/**
          retention-days: 30

      - name: Upload code coverage
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: code-coverage-${{ matrix.test-type }}-${{ matrix.os }}
          path: |
            **/TestResults/**/coverage.*
          retention-days: 30

      - name: Report test results
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: ${{ matrix.test-name }} Report (${{ matrix.os }})
          path: '**/*.trx'
          reporter: dotnet-trx
