name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            filter: --filter "Requires!=SSL"

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Trust developer certificates
        if: matrix.os == 'ubuntu-latest'
        run: dotnet dev-certs https --trust

      - name: Install .NET MAUI
        if: matrix.os == 'ubuntu-latest'
        run: dotnet workload install maui-android

      - name: Install .NET MAUI
        if: matrix.os != 'ubuntu-latest'
        run: dotnet workload install maui

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage" ${{ matrix.filter }}

      - name: Report test results
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Test Report
          path: '**/*.trx'
          reporter: dotnet-trx
